config/routes.rb
VetClinic::Application.routes.draw do
  resources :appointments
  
  resources :pets

  devise_for :users
  namespace :admin do
    resources :users
  end

  root 'appointments#index'
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  PET_TYPES = %w[dog cat bird]

  validates :pet_type, inclusion: Pet::PET_TYPES, presence: true
  validates :breed, length: { in: 3..35 }
  validates :name, length: { in: 3..35 }

  validates_presence_of :age, :weight, :date_last_visit
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_filter :ensure_user_can_manage_pets
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pet }
      else
        format.html { render action: 'new' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :pet_type, :breed, :age, :weight, :date_last_visit)
    end

    def ensure_user_can_manage_pets
      unless current_user.admin? || current_user.doctor?
        flash[:notice] = "You do not have permissions."
        redirect_to appointments_path
      end
    end
end

app/helpers/pets_helper.rb
module PetsHelper

  def available_pet_types
    Pet::PET_TYPES.map{ |pet_type| [pet_type.capitalize, pet_type] }
  end
end

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pet_type %><br>
    <%= f.select :pet_type, available_pet_types %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :date_last_visit %><br>
    <%= f.date_select :date_last_visit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<% if flash[:notice] -%>
 <div id="notice"><%= flash[:notice]%></div>
<% end -%>

<% if flash[:error] -%>
 <div id="error"><%= flash[:error]%></div>
<% end -%>
<h1>Listing pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pet type</th>
      <th>Breed</th>
      <th>Age</th>
      <th>Weight</th>
      <th>Date last visit</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.pet_type %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.age %></td>
        <td><%= pet.weight %></td>
        <td><%= pet.date_last_visit %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Pet type:</strong>
  <%= @pet.pet_type %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pet.weight %>
</p>

<p>
  <strong>Date last visit:</strong>
  <%= @pet.date_last_visit %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>