config/routes.rb
VetClinic::Application.routes.draw do
  resources :appointments
  
  resources :pets

  devise_for :users
  namespace :admin do
    resources :users
  end

  root 'appointments#index'
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :pet
  belongs_to :user
  
  validates_presence_of :pet, :reason_for_visit, :customer, :date_of_visit, :user

  validate :valid_date_of_visit

  private
  def valid_date_of_visit
    if Date.today >= date_of_visit.to_date
      errors.add(:base, "Date of visit cannot be in the past")
    end
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index]
  before_filter :ensure_user_can_manage_appointments, only: [:new, :edit, :update, :create, :destroy]
  before_action :set_pets
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  def index
    @appointments = Appointment.all.includes(:user, :pet)
  end

  def show
  end

  def new
    @appointment = Appointment.new
  end

  def edit
  end

  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @appointment }
      else
        format.html { render action: 'new' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end

  private
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:date_of_visit, :customer, :requires_reminder, :reason_for_visit, :pet_id, :user_id)
    end

   def set_pets
     @pets = Pet.all
   end

   def ensure_user_can_manage_appointments
      unless current_user.receptionist? || current_user.admin?
        flash[:notice] = "You do not have proper permissions"
	redirect_to appointments_path unless current_user.receptionist?
      end
   end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
  def doctors_list
    doctors = User.doctors
    doctors.map {|doctor| [doctor.name, doctor.id]}
  end
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_of_visit %><br>
    <%= f.datetime_select :date_of_visit %>
  </div>
  <div class="field">
    <%= f.select :pet_id, @pets.map{|pet| [pet.name, pet.id]}, prompt: 'Select Pet' %>
  </div>
  <div class="field">
    <%= f.label :customer %><br>
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.select :user_id, doctors_list, prompt: 'Select Doctor' %>
  </div>
  <div class="field">
    <%= f.label :requires_reminder %><br>
    <%= f.check_box :requires_reminder %>
  </div>
  <div class="field">
    <%= f.label :reason_for_visit %><br>
    <%= f.text_field :reason_for_visit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<% if flash[:notice] -%>
 <div id="notice"><%= flash[:notice]%></div>
<% end -%>

<% if flash[:error] -%>
 <div id="error"><%= flash[:error]%></div>
<% end -%>

<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Date of visit</th>
      <th>Customer</th>
      <th>Pet</th>
      <th>Doctor</th>
      <th>Requires reminder</th>
      <th>Reason for visit</th>
      <% if current_user %>
        <th></th>
        <th></th>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date_of_visit %></td>
        <td><%= appointment.customer %></td>
        <td><%= appointment.pet.name%></td>
        <td><%= appointment.user.name%></td>
        <td><%= appointment.requires_reminder %></td>
        <td><%= appointment.reason_for_visit %></td>
        <% if current_user %>
          <td><%= link_to 'Show', appointment %></td>
          <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
          <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date of visit:</strong>
  <%= @appointment.date_of_visit %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @appointment.customer %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @appointment.user.name %>
</p>

<p>
  <strong>Requires reminder:</strong>
  <%= @appointment.requires_reminder %>
</p>

<p>
  <strong>Reason for visit:</strong>
  <%= @appointment.reason_for_visit %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>