config/routes.rb
VetClinic::Application.routes.draw do
  resources :appointments
  
  resources :pets

  devise_for :users
  namespace :admin do
    resources :users
  end

  root 'appointments#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  ROLES = %w[admin doctor receptionist]

  validates :role, inclusion: User::ROLES, presence: true
  validates :name, length: { in: 3..35 }
  validates :zip, length: { maximum: 5 }
  validates :years_in_practice, inclusion: { in: (1..100).to_a }

  before_validation :set_password, on: :create

  scope :doctors, -> { where(role: 'doctor') }

  def admin?
    role? 'admin'
  end

  def doctor?
    role? 'doctor'
  end

  def receptionist?
    role? 'receptionist'
  end

  def role? name
    role == name
  end
  

  private
  def set_password
    self.password = 'welcome123'
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :ensure_user_is_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        puts "Update user successfully"
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        puts "@user #{@user.inspect} #{@user.errors.full_messages}"
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :title, :email, :address, :city, :state, :zip, :school, :years_in_practice, :role)
  end

  def ensure_user_is_admin
    redirect_to appointments_path unless current_user.admin?
  end
end

app/controllers/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :ensure_user_is_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        puts "Update user successfully"
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        puts "@user #{@user.inspect} #{@user.errors.full_messages}"
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :title, :email, :address, :city, :state, :zip, :school, :years_in_practice, :role)
  end

  def ensure_user_is_admin
    redirect_to appointments_path unless current_user.admin?
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def user_roles
    User::ROLES.map{|role| [role.capitalize, role]}
  end

  def user_form_submission_path
    @user.persisted? ? admin_user_path(@user) : admin_users_path
  end
end

app/views/admin/users/_form.html.erb
<%= form_for @user, url: user_form_submission_path do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title%><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :years_in_practice %><br>
    <%= f.text_field :years_in_practice %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.select :role, user_roles, {} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/create.html.erb
<h1>Admin::Users#create</h1>
<p>Find me in app/views/admin/users/create.html.erb</p>

app/views/admin/users/destroy.html.erb
<h1>Admin::Users#destroy</h1>
<p>Find me in app/views/admin/users/destroy.html.erb</p>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<% if flash[:notice] -%>
 <div id="notice"><%= flash[:notice]%></div>
<% end -%>

<% if flash[:error] -%>
 <div id="error"><%= flash[:error]%></div>
<% end -%>

<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.title %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', admin_user_path(user) %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @user.title %>
</p>

<p>
  <strong>Email</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>
<p>
  <strong>State:</strong>
  <%= @user.state%>
</p>

<p>
  <strong>Zip:</strong>
  <%= @user.zip%>
</p>

<p>
  <strong>School:</strong>
  <%= @user.school %>
</p>

<p>
  <strong>Years in Practice:</strong>
  <%= @user.years_in_practice %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/update.html.erb
<h1>Admin::Users#update</h1>
<p>Find me in app/views/admin/users/update.html.erb</p>